package com.sentinel.field.security

/**
 * ============================================================================
 * CANONICAL JSON — byte-identical to `canonicalDeviceJson` in
 * `packages/contracts/src/device-identity.ts`.
 *
 * WHY THIS FILE IS PURE KOTLIN AND IMPORTS NOTHING
 * ------------------------------------------------
 * A signature scheme cannot survive two opinions about what the signed bytes
 * are. The server has one canonicaliser, in the contract, and every WP-23..26
 * statement goes through it. This is the SECOND implementation of it — that is
 * unavoidable, because the phone must produce the same bytes before it can sign
 * them — and the only defence against the two drifting is that this one is
 * pure, has no Android dependency at all, and is tested on the JVM against
 * fixtures generated by the contract's own algorithm running on V8.
 *
 * THE RULES, RESTATED FROM THE CONTRACT
 * -------------------------------------
 *   * object keys sort recursively, by UTF-16 code unit — which is what
 *     `Array.prototype.sort()` does with no comparator and what Kotlin's
 *     `String.compareTo` does. The two orderings are the same ordering.
 *   * ARRAY ORDER IS PRESERVED. Sorting an array would change what the
 *     statement says.
 *   * no whitespace anywhere; `{}` and `[]` for empty containers.
 *   * anything not losslessly representable is REFUSED, never normalised. The
 *     contract throws `TypeError` on a `Date`, a `NaN`, an `Infinity`, a `Map`,
 *     a sparse array or a cycle; this throws [NotCanonicallyRepresentable] on
 *     the Kotlin equivalents, including any floating-point value at all.
 *
 * WHY FLOATING POINT IS REFUSED OUTRIGHT
 * --------------------------------------
 * The contract accepts a finite JS number, but a JS number's textual form comes
 * from V8's shortest-round-trip algorithm, and Kotlin's `Double.toString` does
 * not always agree with it (`1e21`, `5e-324`, integral doubles printing as
 * `1.0` rather than `1`). Reproducing V8's number printing from memory would be
 * a guess in the one place a guess is fatal. NO SENTINEL DEVICE STATEMENT
 * CONTAINS A NON-INTEGER: the only numbers in any of them are `schema_version`,
 * `key_version` and `freshness_ms`, all integers. So integers are supported
 * exactly and everything else is refused loudly.
 * ============================================================================
 */
object CanonicalJson {

    /** Thrown for any value the contract's canonicaliser would also refuse. */
    class NotCanonicallyRepresentable(message: String) : IllegalArgumentException(message)

    private const val FORM_FEED = '\u000C'
    private const val HEX = "0123456789abcdef"

    /**
     * The canonical string for [value].
     *
     * Accepted node types, and only these: `null`, [String], [Boolean], [Int],
     * [Long], [Map] with [String] keys, and [List].
     */
    fun encode(value: Any?): String {
        val out = StringBuilder()
        write(value, out, "value", ArrayList())
        return out.toString()
    }

    /**
     * The open container stack, compared by IDENTITY.
     *
     * It is an [ArrayList] and not a hash set on purpose: putting a
     * self-referential map into a `HashSet` would recurse inside `hashCode()`
     * and blow the stack BEFORE the cycle check could run, turning a clean
     * refusal into a crash.
     */
    private fun containsIdentity(stack: List<Any>, value: Any): Boolean {
        for (index in stack.indices) {
            if (stack[index] === value) return true
        }
        return false
    }

    private fun write(value: Any?, out: StringBuilder, path: String, stack: MutableList<Any>) {
        when (value) {
            null -> out.append("null")
            is String -> writeString(value, out)
            is Boolean -> out.append(if (value) "true" else "false")
            is Int -> out.append(value.toString())
            is Long -> out.append(value.toString())
            is Map<*, *> -> writeObject(value, out, path, stack)
            is List<*> -> writeArray(value, out, path, stack)
            else -> throw NotCanonicallyRepresentable(
                "$path is not canonically representable: ${value.javaClass.name}",
            )
        }
    }

    private fun writeObject(value: Map<*, *>, out: StringBuilder, path: String, stack: MutableList<Any>) {
        if (containsIdentity(stack, value)) {
            throw NotCanonicallyRepresentable("$path is not canonically representable: circular reference")
        }
        stack.add(value)
        val keys = ArrayList<String>(value.size)
        for (key in value.keys) {
            if (key !is String) {
                throw NotCanonicallyRepresentable("$path is not canonically representable: non-string key")
            }
            keys.add(key)
        }
        keys.sort()
        out.append('{')
        var first = true
        for (key in keys) {
            if (!first) out.append(',')
            first = false
            writeString(key, out)
            out.append(':')
            write(value[key], out, "$path.$key", stack)
        }
        out.append('}')
        stack.removeAt(stack.size - 1)
    }

    private fun writeArray(value: List<*>, out: StringBuilder, path: String, stack: MutableList<Any>) {
        if (containsIdentity(stack, value)) {
            throw NotCanonicallyRepresentable("$path is not canonically representable: circular reference")
        }
        stack.add(value)
        out.append('[')
        for (index in value.indices) {
            if (index > 0) out.append(',')
            write(value[index], out, "$path[$index]", stack)
        }
        out.append(']')
        stack.removeAt(stack.size - 1)
    }

    /**
     * `JSON.stringify`'s string escaping, exactly.
     *
     * Verified against V8 for the full set below: `"` and `\` are escaped;
     * 0x08/0x09/0x0A/0x0C/0x0D take their two-character forms; every other
     * character below 0x20 becomes `\u00xx` with LOWERCASE hex; 0x7F (DEL) is
     * NOT escaped; non-ASCII is NOT escaped and is emitted as UTF-8 by the
     * caller. Lone surrogates take the well-formed-stringify escape (ES2019),
     * which no Sentinel statement should ever contain but which must not
     * silently produce different bytes on the two sides if one ever does.
     */
    private fun writeString(value: String, out: StringBuilder) {
        out.append('"')
        var index = 0
        while (index < value.length) {
            val c = value[index]
            when {
                c == '"' -> out.append("\\\"")
                c == '\\' -> out.append("\\\\")
                c == '\b' -> out.append("\\b")
                c == '\t' -> out.append("\\t")
                c == '\n' -> out.append("\\n")
                c == FORM_FEED -> out.append("\\f")
                c == '\r' -> out.append("\\r")
                c < ' ' -> out.append(unicodeEscape(c))
                Character.isHighSurrogate(c) -> {
                    val hasPair = index + 1 < value.length && Character.isLowSurrogate(value[index + 1])
                    if (hasPair) {
                        out.append(c).append(value[index + 1])
                        index += 1
                    } else {
                        out.append(unicodeEscape(c))
                    }
                }
                Character.isLowSurrogate(c) -> out.append(unicodeEscape(c))
                else -> out.append(c)
            }
            index += 1
        }
        out.append('"')
    }

    private fun unicodeEscape(c: Char): String {
        val code = c.code
        return StringBuilder(6)
            .append("\\u")
            .append(HEX[(code shr 12) and 0xF])
            .append(HEX[(code shr 8) and 0xF])
            .append(HEX[(code shr 4) and 0xF])
            .append(HEX[code and 0xF])
            .toString()
    }
}
